BibliotecaAppMVC/Models/ErrorViewModel.cs
namespace BibliotecaAppMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BibliotecaAppMVC/Controllers/HomeController.cs
using BibliotecaAppMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BibliotecaAppMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BibliotecaAppMVC/Controllers/LibrosController.cs
using Biblioteca.Bl;
using BibliotecaEN;
using Microsoft.AspNetCore.Mvc;

namespace BibliotecaAppMVC.Controllers
{
    public class LibrosController : Controller
    {
            LibrosEN LibrosEN = new LibrosEN();
            LibrosBL LibrosBL = new LibrosBL();

            //Metodo que devuelve la vista Index
            public IActionResult Index()
            {
                return View();
            }
            [HttpPost]
            //Metodo que devuelve un JsonResult con la lista de libros
            public JsonResult MostrarLibros()
            {
                return Json(LibrosBL.MostrarLibro());
            }
            //Metodo que devuelve la vista AgregarLibro
            [HttpGet]
            public IActionResult AgregarLibro()
            {
                return View();
            }
            //metodo que realiza la accion de agregar un libro a las N-Capas 
            [HttpPost]
            public IActionResult AgregarLibro(LibrosEN pLibrosEN)
            {
                string mensaje = "";
                if (pLibrosEN != null && pLibrosEN.Titulo != "" && pLibrosEN.Autor != "" && pLibrosEN.AnioPublicacion != 0)
                {
                    if (LibrosBL.AgregarLibro(pLibrosEN) > 0)
                    {
                        mensaje = "Libro agregado correctamente";
                    }
                    else
                    {
                        mensaje = "Error al agregar el libro";
                    }
                }
                else
                {
                    mensaje = "Debe completar todos los campos";
                }
                return Json(new { Mensaje = mensaje });

            }
            //Metodo que devuelve la vista de ModificarLibro
            [HttpGet]
            public IActionResult ModificarLibro(int Id)
            {
                return View();
            }
            //Metodo que realixa la peticion de modificar un libro
            [HttpPost]
            public JsonResult ModificarLibro(LibrosEN pLibrosEN)
            {
                string mensaje = "";
                if (pLibrosEN != null && pLibrosEN.Titulo != "" && pLibrosEN.Autor != "" && pLibrosEN.AnioPublicacion != 0)
                {
                    if (LibrosBL.ModificarLibro(pLibrosEN) > 0)
                    {
                        mensaje = "Libro modificado correctamente";
                    }
                    else
                    {
                        mensaje = "Error al modificar el libro";
                    }
                }
                else
                {
                    mensaje = "Debe completar todos los campos";
                }
                return Json(new { Mensaje = mensaje });
            }
            //Metodo que devuelve la vista EliminarLibro
            [HttpGet]
            public IActionResult EliminarLibro()
            {
                return View();
            }
            //Metodo que realiza la peticion de eliminar un libro
            [HttpPost]
            public JsonResult EliminarLibro(LibrosEN pLibrosEN)
            {
                string mensaje = "";
                if (pLibrosEN.Id != 0)
                {
                    if (LibrosBL.EliminarLibro(pLibrosEN) > 0)
                    {
                        mensaje = "Libro eliminado correctamente";
                    }
                    else
                    {
                        mensaje = "Error al eliminar el libro";
                    }
                }
                else
                {
                    mensaje = "Debe seleccionar un Libro";
                }
                return Json(new { Mensaje = mensaje });
            }
    }
}

BibliotecaAppMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BibliotecaAppMVC/Views/Libros/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

BibliotecaAppMVC/Views/Libros/MostrarLibros.cshtml
@{
    ViewData["Title"] = "MostrarLibros";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h1>Libros Disponibles</h1>
</div>

BibliotecaAppMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BibliotecaAppMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/BibliotecaAppMVC.styles.css" asp-append-version="true" />
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Biblioteca Alejandria</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Resumen</div>
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-home"></i></div>
                            Inicio
                        </a>
                        <a class="nav-link" href="@Url.Action("MostrarLibros", "Libros")">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Libros
                        </a>
                        
                        <div class="sb-sidenav-menu-heading">Prestamos</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-reader"></i></div>
                            Prestamos 
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-undo"></i></div>
                            Devoluciones
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Usuarios
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>

            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/scripts.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>